spryker/event-behavior

- src/Spryker/Zed/EventBehavior/Business/Model/EventEntityTransferFilter.php
- src/Spryker/Zed/EventBehavior/Business/Model/TriggerManager.php
- src/Spryker/Zed/EventBehavior/EventBehaviorConfig.php
- src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainer.php
- src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainerInterface.php
- src/Spryker/Zed/EventBehavior/Persistence/Propel/AbstractSpyEventBehaviorEntityChange.php
* Fix getEventTransfer* issues
* Fix the bugs which brakes install script
> Prepare Event Behaviour for P&S

- src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainer.php
- Developer(s): @ehsanmx
* This release fixed the issue related to missing propel model
_**Patch:** Backwards-compatible bug fix_
Def of done (by responsible developer):
Bugfixes
- Added a check for propel models
> Fix issue when propel model is missing

- .travis.yml
- composer.json
- src/Spryker/Zed/EventBehavior/Persistence/Propel/Schema/spy_event_behavior.schema.xml
- Developer(s): @ehsanmx, @gerner-spryker
- Peer Reviewer:
- Ticket: https://spryker.atlassian.net/browse/CORE-2793
- Ticket: https://spryker.atlassian.net/browse/CORE-2977
- Core PR: 
- Release Overview: -
EventBehavior              | major                |                  |
Changing spy_event_behavior_entity_change primary key type to BIGINT.
_**Mini-Major:** Added functionality with incompatible API changes_
Def of done (by responsible developer):
- Changing spy_event_behavior_entity_change primary key type to BIGINT.
> CORE-2793 Multistore Publish Synchronize

- src/Spryker/Zed/EventBehavior/Persistence/Propel/Behavior/EventBehavior.php
- Developer(s): @m7moud
- Ticket: https://spryker.atlassian.net/browse/PS-5651
- Academy PR: -
- Release Group: https://release.spryker.com/release-groups/view/881
Replaced leaking dependency class with same table for same module.
Bugfixes
- Replaced leaking `SpyAvailabilityAbstractTableMap` class with same table for same module.
- Renamed post save and delete methods.
> PS-5651 SpyAvailabilityAbstractTableMap leaks to all entities

- src/Spryker/Zed/EventBehavior/Business/Model/TriggerManager.php
- src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorPersistenceFactory.php
- src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainer.php
- src/Spryker/Zed/EventBehavior/Persistence/Exception/EventBehaviorQueryNotExistsException.php
- Developer(s): @gechetspr
- Ticket: https://spryker.atlassian.net/browse/TE-547
- Release Group: https://release.spryker.com/release-groups/view/992
Fixed an issue with failing on the fresh install of application.
Bugfixes
Added query class existens check in order to prevent failing on the fresh install of application
> TE-547 [support forum] Class not found during fresh installation of suite

- composer.json
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorBusinessFactory.php
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacade.php
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacadeInterface.php
- src/Spryker/Zed/EventBehavior/Business/ListenerTrigger/ListenerTrigger.php
- src/Spryker/Zed/EventBehavior/Business/ListenerTrigger/ListenerTriggerInterface.php
- src/Spryker/Zed/EventBehavior/Communication/Console/EventBehaviorTriggerTimeoutConsole.php
- src/Spryker/Zed/EventBehavior/Communication/Console/EventTriggerConsole.php
- src/Spryker/Zed/EventBehavior/Communication/Console/EventTriggerListenerConsole.php
- src/Spryker/Zed/EventBehavior/Communication/EventBehaviorCommunicationFactory.php
- src/Spryker/Zed/EventBehavior/Communication/Plugin/Console/EventBehaviorPostHookPlugin.php
- src/Spryker/Zed/EventBehavior/Communication/Plugin/ServiceProvider/EventBehaviorServiceProvider.php
- src/Spryker/Zed/EventBehavior/Dependency/Facade/EventBehaviorToEventBridge.php
- src/Spryker/Zed/EventBehavior/Dependency/Facade/EventBehaviorToEventInterface.php
- src/Spryker/Zed/EventBehavior/Dependency/Service/EventBehaviorToUtilEncodingBridge.php
- src/Spryker/Zed/EventBehavior/Dependency/Service/EventBehaviorToUtilEncodingInterface.php
- src/Spryker/Zed/EventBehavior/EventBehaviorDependencyProvider.php
- Developer(s): @alexanderM91
- Ticket: https://spryker.atlassian.net/browse/TE-657
- Release Group: https://release.spryker.com/release-groups/view/1100
- Release Overview: https://release.spryker.com/core/TE-817 [Replace with actual PR overview link]
EventBehavior                 | minor                 |              Event,  UtilEncoding        |
Introduced a new console command that allows to trigger event processing by listener name.
Improvements
- Introduced a new console command `EventTriggerListenerConsole`.
- Introduced a new method …
> TE-657 debug event listeners command

- src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacade.php
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacadeInterface.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventEntityTransferFilter.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventEntityTransferFilterInterface.php
Epic ticket: https://spryker.atlassian.net/browse/PS-3812
Story ticket: https://spryker.atlassian.net/browse/PS-3814
Bug: https://spryker.atlassian.net/browse/PS-7115
> PS-7115 Multistore - do not show products that are not assigned to the store

- .travis.yml
> Add composer global require hirak/prestissimo

- src/Spryker/Zed/EventBehavior/Business/Model/TriggerManager.php
- Developer(s): @m7moud
- Ticket: https://spryker.atlassian.net/browse/CC-3390
- Academy PR: -
- Release Group: https://release.spryker.com/release-groups/view/1262
{skip}
Bugfixes
- Fix an issue when triggering a delete event.
> CC-3390 Delete event trigger causes exception

- src/Spryker/Zed/EventBehavior/Business/EventBehaviorBusinessFactory.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourcePluginResolver.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourcePluginResolverInterface.php
- Developer(s): @m7moud
- Ticket: https://spryker.atlassian.net/browse/CC-4287
- Academy PR: -
- Release Group: https://release.spryker.com/release-groups/view/1485
Ensure that events are only queued once.
Improvements
- Adjusted `EventResourcePluginResolver` to remove duplicate plugins for the same event and resource.
> CC-4287 Resolve duplicate event plugins

- phpstan.json
- phpstan.neon
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacade.php
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacadeInterface.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourcePluginResolver.php
- src/Spryker/Zed/EventBehavior/Communication/Console/EventBehaviorTriggerTimeoutConsole.php
- src/Spryker/Zed/EventBehavior/Communication/Console/EventTriggerConsole.php
- src/Spryker/Zed/EventBehavior/Dependency/Service/EventBehaviorToUtilEncodingBridge.php
- src/Spryker/Zed/EventBehavior/Dependency/Service/EventBehaviorToUtilEncodingInterface.php
- src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainer.php
- src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainerInterface.php
- src/Spryker/Zed/EventBehavior/Persistence/Propel/AbstractSpyEventBehaviorEntityChange.php
- src/Spryker/Zed/EventBehavior/Persistence/Propel/AbstractSpyEventBehaviorEntityChangeQuery.php
- tests/SprykerTest/Zed/EventBehavior/Business/EventBehaviorFacadeTest.php
- tests/SprykerTest/Zed/EventBehavior/Business/Model/EventResourceQueryContainerManagerTest.php
- tests/SprykerTest/Zed/EventBehavior/_support/EventBehaviorBusinessTester.php
Core PR: https://github.com/spryker/spryker/pull/6127
Suitenonsplit PR: https://github.com/spryker/suite-nonsplit/pull/2989
> TE-4300 Level 5 - rest of modules

- src/Spryker/Zed/EventBehavior/Persistence/Propel/Schema/spy_event_behavior.schema.xml
- Developer(s): @stereomon
- Ticket: https://spryker.atlassian.net/browse/TE-4081
- Release Group: https://release.spryker.com/release-groups/view/1967
Adding index to `spy_event_behavior_entity_change.process_id` column
Improvements
- Added index to column `spy_event_behavior_entity_change.process_id`
> TE-4081 added transaction to read of state and process from DB

- src/Spryker/Shared/EventBehavior/Transfer/event_behavior.transfer.xml
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacade.php
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacadeInterface.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventEntityTransferFilter.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventEntityTransferFilterInterface.php
- src/Spryker/Zed/EventBehavior/Business/Model/TriggerManager.php
- src/Spryker/Zed/EventBehavior/Persistence/Propel/Behavior/EventBehavior.php
- tests/SprykerTest/Zed/EventBehavior/Business/EventBehaviorFacadeTest.php
- Developer(s): @a-sabaa
- Ticket: https://spryker.atlassian.net/browse/MP-1057
- Release Group: URL_HERE
{skip}
Improvements
- Added new parameter behavior to always be able to send additional column values with any event triggered by the event behavior.
> MP-1057: MP-1256: Created posibility for sending additional fields

- tests/SprykerTest/Zed/EventBehavior/Business/EventBehaviorFacadeTest.php
- tests/SprykerTest/Zed/EventBehavior/Business/Model/EventResourceQueryContainerManagerTest.php
https://spryker.atlassian.net/browse/TE-4488
> Make tests CS strict

- src/Spryker/Zed/EventBehavior/Persistence/Propel/Behavior/EventBehavior.php
- Developer(s): @AsonUnique
- Ticket: https://spryker.atlassian.net/browse/CC-7313
- Release Group: https://release.spryker.com/release-groups/view/2134
{skip}
Bugfixes
- Adjusted generated code template so Propel instance pooling will be disabled during `SpyEventBehaviorEntityChange` saving.
> CC-7313 Product relation update leads to memory leak

- src/Spryker/Shared/EventBehavior/EventBehaviorConstants.php
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorBusinessFactory.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourcePluginResolver.php
- src/Spryker/Zed/EventBehavior/EventBehaviorConfig.php
- Developer(s): @gechetspr
- Ticket: https://spryker.atlassian.net/browse/TE-4600
- Release Group: https://release.spryker.com/release-groups/view/2324
{skip}
Improvements
- Introduced `EventBehaviorConstants::ENABLE_INSTANCE_POOLING` for configuring instance pooling on event triggering.
- Adjusted `EventResourceRepositoryManager` in order to use new configuration value.
> TE-4600 Product Concrete event trigger memory leak

- composer.json
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourcePluginResolver.php
- Developer(s): @artem-png
- Ticket: https://spryker.atlassian.net/browse/CC-9083
- Release Group: https://release.spryker.com/release-groups/view/2622
Improvements
- Increased Kernel module version dependency.
- Adjusted `EventResourcePluginResolver` to use `InstancePoolingTrait` instead of using `Propel` methods.
> CC-9083: Queue worker stucks

- src/Spryker/Zed/EventBehavior/Business/Model/EventResourcePluginResolver.php
- Developer(s): @alexanderM91
- Ticket: https://spryker.atlassian.net/browse/TE-496
- Release Group: https://release.spryker.com/release-groups/view/2714
{skip}
Bugfixes
- Fixed `EventBehaviorFacadeInterface::getAvailableResourceNames()` resource names list from plugins configured in `EventBehaviorDependencyProvider::getEventTriggerResourcePlugins()` and `PublisherDependencyProvider::getPublisherTriggerPlugins()`.
> TE-496: Available resource list

- src/Spryker/Zed/EventBehavior/EventBehaviorDependencyProvider.php
- src/Spryker/Zed/EventBehavior/Persistence/Propel/Schema/spy_event_behavior.schema.xml
- Developer(s): @alexanderM91
- Ticket: https://spryker.atlassian.net/browse/SC-4968
- Release Group: https://release.spryker.com/release-groups/view/3021
- Added missing `size` property into `spy_event_behavior_entity_change.process_id` column.
- Refactored `ContainerInterface` array access usage to `ContainerInterface::set()` method usage.
> SC-4968: Update schema with missed size property

- composer.json
- src/Spryker/Zed/EventBehavior/Persistence/Propel/Behavior/EventBehavior.php
- Developer(s): @romanhavrylko
- Ticket: https://spryker.atlassian.net/browse/TE-7666
EventBehavior           | minor                 | Laminas               |
> TE-7819 Replaced Zend usage

- composer.json
- dependency.json
- Developer(s): @AsonUnique
- Ticket: https://spryker.atlassian.net/browse/TE-7664
- Release Group: https://release.spryker.com/release-groups/view/3112
EventBehavior         | patch {skip}          |                       |
> TE-7664 Fix travis issues

- composer.json
- phpstan.neon
- src/Spryker/Shared/EventBehavior/Transfer/event_behavior.transfer.xml
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacade.php
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacadeInterface.php
- src/Spryker/Zed/EventBehavior/Business/Model/TriggerManager.php
- src/Spryker/Zed/EventBehavior/Business/Model/TriggerManagerInterface.php
- src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainerInterface.php
- tests/SprykerTest/Zed/EventBehavior/_support/Helper/EventBehaviorHelper.php
- tests/SprykerTest/Zed/EventBehavior/_support/Helper/EventBehaviorHelperTrait.php
- Developer(s): @stereomon
- Ticket: https://spryker.atlassian.net/browse/TE-8573
- Release Group: https://release.spryker.com/release-groups/view/3385
- merge: merge
Improvements
- Added `EventBehaviorHelper` for easier testing.
- Introduced `EventBehaviorFacade::triggerRuntimeEventsWithReport()` with a `EventTriggerResponseTransfer` as return type for debugging purposes.
> TE-8573 P&S testing infrastructure

- .github/workflows/ci.yml
- .gitignore
- ci/config_default.php
- ci/default_store.php
- ci/stores.php
- codeception.yml
- composer.json
- dependency.json
- phpstan.json
- phpstan.neon
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacade.php
- src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacadeInterface.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourceManagerInterface.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourcePluginResolver.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourcePluginResolverInterface.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourceQueryContainerPluginIterator.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourceRepositoryManager.php
- src/Spryker/Zed/EventBehavior/Communication/Console/EventBehaviorTriggerTimeoutConsole.php
- src/Spryker/Zed/EventBehavior/Communication/Console/EventTriggerConsole.php
- src/Spryker/Zed/EventBehavior/Communication/Console/EventTriggerListenerConsole.php
- src/Spryker/Zed/EventBehavior/Dependency/Plugin/EventResourceQueryContainerPluginInterface.php
- src/Spryker/Zed/EventBehavior/Dependency/Plugin/EventResourceRepositoryPluginInterface.php
- tests/SprykerTest/Zed/EventBehavior/codeception.yml
- tests/bootstrap.php
so far `composer test` is failing due to
```
[Error] Class 'Orm\Zed\EventBehavior\Persistence\SpyEventBehaviorEntityChangeQuery' not found                                                
```
What are we missing here?
Adding `\SprykerTest\Shared\Propel\Helper\PropelInstallHelper` still reports
```
The "/var/work/devvm/project/vendor/spryker/event-behavior/
tests/SprykerTest/Zed/EventBehavior/src/Spryker/Zed/*/Persistence/Propel/Schema" 
directory does not exist. 
```
https://spryker.atlassian.net/browse/TE-10185
> TE-10185 Fix up testing harness.

- architecture-baseline.json
- src/Spryker/Zed/EventBehavior/Dependency/Facade/EventBehaviorToEventBridge.php
- src/Spryker/Zed/EventBehavior/Dependency/Facade/EventBehaviorToEventInterface.php
> Fix violation

- architecture-baseline.json
Ticker: https://spryker.atlassian.net/browse/TE-10704
Architecture sniffer PR: https://github.com/spryker/architecture-sniffer/pull/109
> TE-10704 Fixed message about not supported return type and added message for absent param type

- phpstan.neon
- src/Spryker/Zed/EventBehavior/Business/Model/AbstractEventResourcePluginIterator.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourceQueryContainerPluginIterator.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourceRepositoryBulkPluginIterator.php
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourceRepositoryPluginIterator.php
- src/Spryker/Zed/EventBehavior/Business/Model/TriggerManager.php
Ticket: https://spryker.atlassian.net/browse/TE-10993
> TE-10993 Fix up generics phpdoc-blocks.

- composer.json
- src/Spryker/Zed/EventBehavior/Persistence/Propel/AbstractSpyEventBehaviorEntityChange.php
- src/Spryker/Zed/EventBehavior/Persistence/Propel/Behavior/EventBehavior.php
- Developer(s): @limeeugenia
- Ticket: https://spryker.atlassian.net/browse/TE-10478
- Release Group: https://release.spryker.com/release-groups/view/4239
- merge: merge
Improvements
- Updated @spryker/propel-orm dependency.
- Adjusted `EventBehavior::addParameter()` in order to be compatible with new Propel release.
- Adjusted `AbstractSpyEventBehaviorEntityChange` in order to be compatible with new Propel release.
> TE-10478 Added new Propel release compatibility.

- .github/workflows/ci.yml
- README.md
- ci/config_default.php
- ci/config_propel.php
- composer.json
- dependency.json
- phpstan.neon
- src/Spryker/Zed/EventBehavior/Business/Model/EventResourceQueryContainerPluginIterator.php
- src/Spryker/Zed/EventBehavior/Persistence/Propel/Behavior/EventBehavior.php
- tests/SprykerTest/Zed/EventBehavior/codeception.yml
- tests/bootstrap.php
Ticket: https://spryker.atlassian.net/browse/FRW-332
> FRW-332 Change min PHP version to 8.0

- .github/workflows/ci.yml
- composer.json
Removed library usage until further change to the release process is made
> Removed composer validate lowest check from CI

- CONTRIBUTING.md
https://spryker.atlassian.net/browse/FRW-8526
> FRW-8526 Adjusted CONTRIBUTING.md.

- .github/workflows/ci.yml
- README.md
- composer.json
- phpcs.xml
- Developer(s): @olhalivitchuk  
- Ticket: https://spryker.atlassian.net/browse/FRW-8801
- Release Group: https://release.spryker.com/release-groups/view/5551
- PR Overview: https://release.spryker.com/release/pull-request-core/EventBehavior/92
- merge: squash
EventBehavior             | minor          |                       |
Improvements 
- Added `PHP 8.3` support.
> FRW-8801 Dropped PHP 8.1 support.
